require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Until https://github.com/rubocop/rubocop/issues/12430 is fixed
Style/RedundantLineContinuation:
  Enabled: false
