language: ruby
rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2.9
- 2.1.10
before_install: gem update --system
env:
  global:
  - secure: a9jYGrcTq29gjgOJvdZ7UmgbgqRQ6NnxjzAYnZRMieIgoLRwqIYE2DXgiaiNNHI8Xs+SoFk1XSMaE2Rm0zWkJNSAgFHNWi3M50TBE2ZgS/HsDvlItbD/pwrOMHHDjCzAIjLn1uTlUO6xW8T1g0uiIQKdCjMCFsjk7tTqfIrSjQuRiFbUiqHJ4HdOFZsLLJS8ol/Q8TxjpJARdyFUoJ5XYZUScHCfLW5Dt2ZliQ57V+wMyknNt9GjMul25ejclh6FVlATQDc/lZUBOnWwBcZUURzKmKO2ahnYGiJ4FABPAC/1DjFdPmrySXYhjoaSLh9/ZY6bI8QLSCLjCagIbaeIIEdLomBDkOskeE8R6FEaZYAd9C0PDHEky2Tl9aO5I/cvGGX7OUCGQlLcvBXqY4UPzL9WKvdHPBRLclN/4xV8gtc67/nb7UO6NzYGaAAikZlRaDcaSceOwvu2mFZv78OXWY3eMItTQNDETHS/3EfnY5o55t5YnE8b83yaW/2IafYb/QQVy3yCUEZ2vENPxzhO2w5r9VekDVC7EkXS72kT/8yTO4N6aFMfOZXEIAxMgbbOseA6+IKlMnqbihhzjm5qwOsVWTuyHcUkEh8dFBT0uzK84KiSe/EsW02+rAXsfRgAqQ/ILM2b55yJ8+76xktTIDL+0ZHs3yQzzRkHQij4UMw=
  - secure: WUxaj8nGtAwo+12PYXZ5yC10+lM4Fhh4argrafM9jnkXOK+TOLVTBZw8oXYY+oJ8TZHa13MmWs7xZL2z08S9KvtlZFWexBeF7/fbg8piIgX7xbYOLhxFbxbQqUYxDf5d2zWWph+kBtY/6y5intAyDDYOAhoOj1oviE0MZJY2sY/jUSuckBOlUF3ID7fbIqePw7UByFjkWfEK+HmLCOtF0XWkaxigzNg4mT1HXA4aC6aedFxqDo1uHO+IHjoHGmwkeCotTWBdULFwIluPeYSkctA2DOdg/jezEBz2WSMkDTfqx3+cE1PjjnS9Xt/30ePmb+S4XkLoZSTm6cM6tHU2sAxgzm1NRHy8WYbaitE5ThehojY7mZgxuNz8P6MBcufIUVta7tCvOxeeD5nh3p1RqRig2oKRieM1BWk9QkVo1+RscvQKWiTPCmUiTjUB5ZPKhN9L2D8HJRTfjNuSchrmqO3L9Kf22rlNRzqXTt/nOOwzJur9mJa1HsGMNuyZ0eLkcN0EnvJ2gF1WDVcMY4rJb2pkTS6cz6OrsiK2c9YEdZWb2Iy/ZiW0USIXolYC0FKT7AjK0qm9fI8J5dniBas8KlovKbbAw5v2uHugoeUvOwAI8jLoOL6Z3dM2c8LfBvucgsQYE7tNVkUHghb6Deh5h/G0vADVurleg3wUHqaM1Ik=
